name: Generate Snake

on:
  # S'exécute automatiquement toutes les 6 heures
  schedule:
    - cron: "0 */6 * * *"
  # Permet de l'exécuter manuellement si besoin
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v3
        with:
          # Ton nom d'utilisateur GitHub
          github_user_name: Rigel16
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
